import { v4 as uuidv4 } from 'uuid';
import { addDays, format } from 'date-fns';
import type {
  Project,
  Task,
  Dependency,
  CustomFieldDefinition,
  CustomFieldValue,
  User,
  AuditEvent,
} from '../types';

const today = new Date();
const toISO = (d: Date) => format(d, 'yyyy-MM-dd');

// Users
export const sampleUsers: User[] = [
  { id: 'u1', name: 'Alice Chen', email: 'alice@example.com', role: 'project_admin' },
  { id: 'u2', name: 'Bob Martinez', email: 'bob@example.com', role: 'editor' },
  { id: 'u3', name: 'Carol Davis', email: 'carol@example.com', role: 'editor' },
  { id: 'u4', name: 'Dan Wilson', email: 'dan@example.com', role: 'viewer' },
];

// Project
const projectId = 'proj-1';
export const sampleProject: Project = {
  id: projectId,
  workspaceId: 'ws-1',
  name: 'Website Redesign',
  description: 'Complete redesign and relaunch of the company website',
  startDate: toISO(today),
  endDate: toISO(addDays(today, 90)),
  schedulingMode: 'warn',
  defaultZoom: 'week',
  createdBy: 'u1',
  createdAt: toISO(today),
};

// Task IDs
const t1 = uuidv4();
const t2 = uuidv4();
const t3 = uuidv4();
const t4 = uuidv4();
const t5 = uuidv4();
const t6 = uuidv4();
const t7 = uuidv4();
const t8 = uuidv4();
const t9 = uuidv4();
const t10 = uuidv4();
const t11 = uuidv4();
const t12 = uuidv4();
const t13 = uuidv4();
const t14 = uuidv4();

export const sampleTasks: Task[] = [
  // Phase 1: Discovery (summary)
  {
    id: t1,
    projectId,
    parentId: null,
    type: 'summary',
    title: 'Discovery & Planning',
    description: '',
    startDate: toISO(today),
    endDate: toISO(addDays(today, 14)),
    duration: 14,
    ownerUserId: 'u1',
    ownerText: 'Alice Chen',
    status: 'In Progress',
    rag: 'green',
    percentComplete: 60,
    color: '#3b82f6',
    notes: '',
    tags: ['planning'],
    orderIndex: 0,
    splits: [],
    collapsed: false,
    createdBy: 'u1',
    createdAt: toISO(today),
    updatedAt: toISO(today),
  },
  {
    id: t2,
    projectId,
    parentId: t1,
    type: 'task',
    title: 'Stakeholder interviews',
    description: 'Interview key stakeholders',
    startDate: toISO(today),
    endDate: toISO(addDays(today, 5)),
    duration: 5,
    ownerUserId: 'u1',
    ownerText: 'Alice Chen',
    status: 'Complete',
    rag: 'green',
    percentComplete: 100,
    color: '#3b82f6',
    notes: 'All 8 interviews completed. Key findings documented.',
    tags: ['planning', 'research'],
    orderIndex: 1,
    splits: [],
    collapsed: false,
    createdBy: 'u1',
    createdAt: toISO(today),
    updatedAt: toISO(today),
  },
  {
    id: t3,
    projectId,
    parentId: t1,
    type: 'task',
    title: 'Requirements gathering',
    description: 'Document all requirements',
    startDate: toISO(addDays(today, 3)),
    endDate: toISO(addDays(today, 10)),
    duration: 7,
    ownerUserId: 'u2',
    ownerText: 'Bob Martinez',
    status: 'In Progress',
    rag: 'green',
    percentComplete: 40,
    color: '#3b82f6',
    notes: '',
    tags: ['planning'],
    orderIndex: 2,
    splits: [],
    collapsed: false,
    createdBy: 'u1',
    createdAt: toISO(today),
    updatedAt: toISO(today),
  },
  {
    id: t4,
    projectId,
    parentId: t1,
    type: 'milestone',
    title: 'Requirements sign-off',
    description: '',
    startDate: toISO(addDays(today, 14)),
    endDate: toISO(addDays(today, 14)),
    duration: 0,
    ownerUserId: 'u1',
    ownerText: 'Alice Chen',
    status: 'Not Started',
    rag: 'none',
    percentComplete: 0,
    color: '#8b5cf6',
    notes: '',
    tags: ['milestone'],
    orderIndex: 3,
    splits: [],
    collapsed: false,
    createdBy: 'u1',
    createdAt: toISO(today),
    updatedAt: toISO(today),
  },
  // Phase 2: Design (summary)
  {
    id: t5,
    projectId,
    parentId: null,
    type: 'summary',
    title: 'Design',
    description: '',
    startDate: toISO(addDays(today, 15)),
    endDate: toISO(addDays(today, 35)),
    duration: 20,
    ownerUserId: 'u3',
    ownerText: 'Carol Davis',
    status: 'Not Started',
    rag: 'none',
    percentComplete: 0,
    color: '#22c55e',
    notes: '',
    tags: ['design'],
    orderIndex: 4,
    splits: [],
    collapsed: false,
    createdBy: 'u1',
    createdAt: toISO(today),
    updatedAt: toISO(today),
  },
  {
    id: t6,
    projectId,
    parentId: t5,
    type: 'task',
    title: 'Wireframes',
    description: 'Create wireframes for all pages',
    startDate: toISO(addDays(today, 15)),
    endDate: toISO(addDays(today, 22)),
    duration: 7,
    ownerUserId: 'u3',
    ownerText: 'Carol Davis',
    status: 'Not Started',
    rag: 'none',
    percentComplete: 0,
    color: '#22c55e',
    notes: '',
    tags: ['design'],
    orderIndex: 5,
    splits: [],
    collapsed: false,
    createdBy: 'u1',
    createdAt: toISO(today),
    updatedAt: toISO(today),
  },
  {
    id: t7,
    projectId,
    parentId: t5,
    type: 'task',
    title: 'Visual design mockups',
    description: 'High-fidelity designs',
    startDate: toISO(addDays(today, 22)),
    endDate: toISO(addDays(today, 32)),
    duration: 10,
    ownerUserId: 'u3',
    ownerText: 'Carol Davis',
    status: 'Not Started',
    rag: 'amber',
    percentComplete: 0,
    color: '#22c55e',
    notes: 'Waiting for brand guidelines update',
    tags: ['design'],
    orderIndex: 6,
    splits: [],
    collapsed: false,
    createdBy: 'u1',
    createdAt: toISO(today),
    updatedAt: toISO(today),
  },
  {
    id: t8,
    projectId,
    parentId: t5,
    type: 'milestone',
    title: 'Design approval',
    description: '',
    startDate: toISO(addDays(today, 35)),
    endDate: toISO(addDays(today, 35)),
    duration: 0,
    ownerUserId: 'u1',
    ownerText: 'Alice Chen',
    status: 'Not Started',
    rag: 'none',
    percentComplete: 0,
    color: '#8b5cf6',
    notes: '',
    tags: ['milestone'],
    orderIndex: 7,
    splits: [],
    collapsed: false,
    createdBy: 'u1',
    createdAt: toISO(today),
    updatedAt: toISO(today),
  },
  // Phase 3: Development (summary)
  {
    id: t9,
    projectId,
    parentId: null,
    type: 'summary',
    title: 'Development',
    description: '',
    startDate: toISO(addDays(today, 36)),
    endDate: toISO(addDays(today, 70)),
    duration: 34,
    ownerUserId: 'u2',
    ownerText: 'Bob Martinez',
    status: 'Not Started',
    rag: 'none',
    percentComplete: 0,
    color: '#f59e0b',
    notes: '',
    tags: ['development'],
    orderIndex: 8,
    splits: [],
    collapsed: false,
    createdBy: 'u1',
    createdAt: toISO(today),
    updatedAt: toISO(today),
  },
  {
    id: t10,
    projectId,
    parentId: t9,
    type: 'task',
    title: 'Frontend development',
    description: 'Build React components',
    startDate: toISO(addDays(today, 36)),
    endDate: toISO(addDays(today, 56)),
    duration: 20,
    ownerUserId: 'u2',
    ownerText: 'Bob Martinez',
    status: 'Not Started',
    rag: 'none',
    percentComplete: 0,
    color: '#f59e0b',
    notes: '',
    tags: ['development', 'frontend'],
    orderIndex: 9,
    splits: [],
    collapsed: false,
    createdBy: 'u1',
    createdAt: toISO(today),
    updatedAt: toISO(today),
  },
  {
    id: t11,
    projectId,
    parentId: t9,
    type: 'task',
    title: 'Backend API development',
    description: 'Build REST APIs',
    startDate: toISO(addDays(today, 36)),
    endDate: toISO(addDays(today, 52)),
    duration: 16,
    ownerUserId: 'u3',
    ownerText: 'Carol Davis',
    status: 'Not Started',
    rag: 'red',
    percentComplete: 0,
    color: '#f59e0b',
    notes: 'Tech stack decision pending',
    tags: ['development', 'backend'],
    orderIndex: 10,
    splits: [],
    collapsed: false,
    createdBy: 'u1',
    createdAt: toISO(today),
    updatedAt: toISO(today),
  },
  {
    id: t12,
    projectId,
    parentId: t9,
    type: 'task',
    title: 'Integration testing',
    description: 'End-to-end testing',
    startDate: toISO(addDays(today, 56)),
    endDate: toISO(addDays(today, 66)),
    duration: 10,
    ownerUserId: 'u2',
    ownerText: 'Bob Martinez',
    status: 'Not Started',
    rag: 'none',
    percentComplete: 0,
    color: '#f59e0b',
    notes: '',
    tags: ['development', 'testing'],
    orderIndex: 11,
    splits: [],
    collapsed: false,
    createdBy: 'u1',
    createdAt: toISO(today),
    updatedAt: toISO(today),
  },
  // Phase 4: Launch
  {
    id: t13,
    projectId,
    parentId: null,
    type: 'task',
    title: 'UAT & Bug fixes',
    description: 'User acceptance testing',
    startDate: toISO(addDays(today, 70)),
    endDate: toISO(addDays(today, 80)),
    duration: 10,
    ownerUserId: 'u1',
    ownerText: 'Alice Chen',
    status: 'Not Started',
    rag: 'none',
    percentComplete: 0,
    color: '#ef4444',
    notes: '',
    tags: ['testing', 'launch'],
    orderIndex: 12,
    splits: [],
    collapsed: false,
    createdBy: 'u1',
    createdAt: toISO(today),
    updatedAt: toISO(today),
  },
  {
    id: t14,
    projectId,
    parentId: null,
    type: 'milestone',
    title: 'Go Live',
    description: 'Production launch',
    startDate: toISO(addDays(today, 85)),
    endDate: toISO(addDays(today, 85)),
    duration: 0,
    ownerUserId: 'u1',
    ownerText: 'Alice Chen',
    status: 'Not Started',
    rag: 'none',
    percentComplete: 0,
    color: '#ec4899',
    notes: '',
    tags: ['milestone', 'launch'],
    orderIndex: 13,
    splits: [],
    collapsed: false,
    createdBy: 'u1',
    createdAt: toISO(today),
    updatedAt: toISO(today),
  },
];

// Dependencies
export const sampleDependencies: Dependency[] = [
  {
    id: uuidv4(),
    projectId,
    predecessorTaskId: t2,
    successorTaskId: t3,
    type: 'FS',
    lagDays: 0,
    createdAt: toISO(today),
  },
  {
    id: uuidv4(),
    projectId,
    predecessorTaskId: t3,
    successorTaskId: t4,
    type: 'FS',
    lagDays: 0,
    createdAt: toISO(today),
  },
  {
    id: uuidv4(),
    projectId,
    predecessorTaskId: t4,
    successorTaskId: t6,
    type: 'FS',
    lagDays: 0,
    createdAt: toISO(today),
  },
  {
    id: uuidv4(),
    projectId,
    predecessorTaskId: t6,
    successorTaskId: t7,
    type: 'FS',
    lagDays: 0,
    createdAt: toISO(today),
  },
  {
    id: uuidv4(),
    projectId,
    predecessorTaskId: t7,
    successorTaskId: t8,
    type: 'FS',
    lagDays: 0,
    createdAt: toISO(today),
  },
  {
    id: uuidv4(),
    projectId,
    predecessorTaskId: t8,
    successorTaskId: t10,
    type: 'FS',
    lagDays: 0,
    createdAt: toISO(today),
  },
  {
    id: uuidv4(),
    projectId,
    predecessorTaskId: t8,
    successorTaskId: t11,
    type: 'FS',
    lagDays: 0,
    createdAt: toISO(today),
  },
  {
    id: uuidv4(),
    projectId,
    predecessorTaskId: t10,
    successorTaskId: t12,
    type: 'FS',
    lagDays: 0,
    createdAt: toISO(today),
  },
  {
    id: uuidv4(),
    projectId,
    predecessorTaskId: t11,
    successorTaskId: t12,
    type: 'FS',
    lagDays: 0,
    createdAt: toISO(today),
  },
  {
    id: uuidv4(),
    projectId,
    predecessorTaskId: t12,
    successorTaskId: t13,
    type: 'FS',
    lagDays: 0,
    createdAt: toISO(today),
  },
  {
    id: uuidv4(),
    projectId,
    predecessorTaskId: t13,
    successorTaskId: t14,
    type: 'FS',
    lagDays: 0,
    createdAt: toISO(today),
  },
];

// Custom Fields
const cf1 = uuidv4();
const cf2 = uuidv4();
const cf3 = uuidv4();
const cf4 = uuidv4();
const cf5 = uuidv4();

export const sampleCustomFields: CustomFieldDefinition[] = [
  {
    id: cf1,
    scope: 'project',
    scopeId: projectId,
    name: 'Workstream',
    key: 'workstream',
    fieldType: 'dropdown',
    options: ['Frontend', 'Backend', 'Design', 'DevOps', 'QA'],
    required: false,
    visibleByDefault: true,
  },
  {
    id: cf2,
    scope: 'project',
    scopeId: projectId,
    name: 'Priority',
    key: 'priority',
    fieldType: 'dropdown',
    options: ['Critical', 'High', 'Medium', 'Low'],
    required: false,
    visibleByDefault: true,
  },
  {
    id: cf3,
    scope: 'project',
    scopeId: projectId,
    name: 'Estimated Hours',
    key: 'estimated_hours',
    fieldType: 'number',
    options: [],
    required: false,
    visibleByDefault: false,
  },
  {
    id: cf4,
    scope: 'project',
    scopeId: projectId,
    name: 'External Link',
    key: 'external_link',
    fieldType: 'url',
    options: [],
    required: false,
    visibleByDefault: false,
  },
  {
    id: cf5,
    scope: 'project',
    scopeId: projectId,
    name: 'Approved',
    key: 'approved',
    fieldType: 'boolean',
    options: [],
    required: false,
    visibleByDefault: false,
  },
];

export const sampleCustomFieldValues: CustomFieldValue[] = [
  { id: uuidv4(), taskId: t2, fieldDefinitionId: cf1, value: 'Design' },
  { id: uuidv4(), taskId: t3, fieldDefinitionId: cf1, value: 'Frontend' },
  { id: uuidv4(), taskId: t6, fieldDefinitionId: cf1, value: 'Design' },
  { id: uuidv4(), taskId: t7, fieldDefinitionId: cf1, value: 'Design' },
  { id: uuidv4(), taskId: t10, fieldDefinitionId: cf1, value: 'Frontend' },
  { id: uuidv4(), taskId: t11, fieldDefinitionId: cf1, value: 'Backend' },
  { id: uuidv4(), taskId: t12, fieldDefinitionId: cf1, value: 'QA' },
  { id: uuidv4(), taskId: t2, fieldDefinitionId: cf2, value: 'High' },
  { id: uuidv4(), taskId: t3, fieldDefinitionId: cf2, value: 'Critical' },
  { id: uuidv4(), taskId: t10, fieldDefinitionId: cf2, value: 'High' },
  { id: uuidv4(), taskId: t11, fieldDefinitionId: cf2, value: 'High' },
  { id: uuidv4(), taskId: t2, fieldDefinitionId: cf3, value: '40' },
  { id: uuidv4(), taskId: t3, fieldDefinitionId: cf3, value: '56' },
];

export const sampleAuditEvents: AuditEvent[] = [];
